[phases.setup]
nixPkgs = ["jdk21"]

[phases.build]
cmds = ["./mvnw clean install -DskipTests -Dspring.profiles.active=production"]

[start]
cmd = "java -Dserver.port=$PORT -Dspring.profiles.active=production -jar target/*.jar"
